version: '3.8'

services:
  activemq:
    image: apache/activemq-artemis:latest
    container_name: activemq
    ports:
      - "8161:8161" # Web Console
      - "61616:61616" # OpenWire
      - "5672:5672" # AMQP
      - "1883:1883" # MQTT
      - "61613:61613" # STOMP
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
    volumes:
      - activemq_data:/data/activemq
      - activemq_log:/var/log/activemq

volumes:
  activemq_data:
  activemq_log:
