version: '3.8'

services:
  activemq:
    image: apache/activemq-artemis:latest
    container_name: activemq
    ports:
      - "8161:8161" # Web Console
      - "61616:61616" # OpenWire
      - "5672:5672" # AMQP
      - "1883:1883" # MQTT
      - "61613:61613" # STOMP
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
    volumes:
      - activemq_data:/data/activemq
      - activemq_log:/var/log/activemq
  postgres:
    container_name: postgres
    image: bitnami/postgresql:16.4.0-debian-12-r9
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=random_walk_postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

volumes:
  activemq_data:
  activemq_log:
  db_data:
