spring:
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    consumer:
      group-id: "chat-service"
      max-poll-records: 10
      auto-offset-reset: latest
      enable-auto-commit: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
            tablePrefix: QRTZ_
            clusterCheckinInterval: 5000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadsInheritContextClassLoaderOfInitializingThread: true
      auto-startup: false
  jpa:
    show-sql: ${LOGGING_SHOW_JPA_QUERIES:true}
    properties:
      hibernate:
        format_sql: ${LOGGING_SHOW_JPA_QUERIES:true}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/random_walk_postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      schema: chat
  application:
    name: "Chat service"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_URL:http://localhost:8081}
  flyway:
    locations: ${FLYWAY_MIGRATION_LOCATIONS:classpath:db/local_migration,classpath:db/migration}
    baseline-on-migrate: true
broker:
  host: ${ACTIVEMQ_ARTEMIS_HOST:localhost}
  port: 61613
  login: ${ACTIVEMQ_ARTEMIS_LOGIN:admin}
  password: ${ACTIVEMQ_ARTEMIS_PASSWORD:admin}
server:
  port: 8080
logging:
  level:
    ru.random.walk.chat_service: ${GENERAL_LOGGING_LEVEL:DEBUG}
    org.hibernate.orm.jdbc.bind: ${LOGGING_SHOW_BINDING_JPA_VALUES_LEVEL:TRACE}
inter:
  matcher:
    url: ${MATCHER_URL:http://localhost:8082}
  auth:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}
    login: ${INTER_CHAT_LOGIN:CLUB_TEST_CLIENT}
    password: ${INTER_CHAT_PASSWORD:1234Club}
outbox:
  job:
    startIntervalInSeconds: 5