spring:
  flyway:
    default-schema: chat
    table: flyway_schema_history
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${RANDOM_WALK_POSTGRES_URL:jdbc:postgresql://localhost:5432/random_walk_postgres}
    username: ${RANDOM_WALK_POSTGRES_USERNAME:postgres}
    password: ${RANDOM_WALK_POSTGRES_PASSWORD:postgres}
  application:
    name: "Chat service"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_URL:http://localhost:8081}
broker:
  host: ${ACTIVEMQ_ARTEMIS_HOST:localhost}
  port: 61613
  login: ${ACTIVEMQ_ARTEMIS_LOGIN:admin}
  password: ${ACTIVEMQ_ARTEMIS_PASSWORD:admin}
server:
  port: 8080